"""
Deterministic FastAPI OpenAPI schema dumper.

Invoked by `.husky/pre-commit` via `scripts/openapi_hook_gate.sh` whenever
any file under `backend/app/routers/` is staged. Its output must be
deterministic across runs (sorted keys, no timestamps).

Canonical invocation:
    cd backend && uv run python scripts/dump_openapi.py

The gate script handles env-var injection before calling this script, so
any contributor can commit router changes without a full `.env` configured.
"""

import json
import os
import sys
from datetime import UTC, datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]  # backend/scripts -> backend -> repo root
DOCS_API_DIR = REPO_ROOT / "docs" / "api"
OPENAPI_JSON = DOCS_API_DIR / "openapi.json"
ENDPOINTS_MD = DOCS_API_DIR / "endpoints.md"

# ---------------------------------------------------------------------------
# Required env vars (pydantic-settings BaseSettings demands these at import)
# ---------------------------------------------------------------------------
REQUIRED_VARS = [
    "DATABASE_URL",
    "SUPABASE_URL",
    "SUPABASE_SERVICE_ROLE_KEY",
    "GEMINI_API_KEY",
    "VAPID_PUBLIC_KEY",
    "VAPID_PRIVATE_KEY",
    "VAPID_EMAIL",
]


def _check_env() -> None:
    missing = [v for v in REQUIRED_VARS if not os.environ.get(v)]
    if missing:
        print(
            f"[dump_openapi] FATAL: required env vars missing: {', '.join(missing)}.\n"
            "Source .env.test.example (or .env) before running, e.g.:\n"
            "  set -a && source ../.env.test.example && set +a && "
            "uv run python scripts/dump_openapi.py",
            file=sys.stderr,
        )
        sys.exit(2)


def _import_app():
    try:
        from app.main import app  # noqa: PLC0415

        return app
    except Exception as exc:
        print(f"[dump_openapi] FATAL: failed to import app.main: {exc}", file=sys.stderr)
        sys.exit(2)


def _deterministic_schema(schema: dict) -> dict:
    """Sort paths, methods, tags and component schemas for deterministic output."""
    if "paths" in schema:
        sorted_paths = {}
        for path in sorted(schema["paths"]):
            methods = schema["paths"][path]
            sorted_paths[path] = {m: methods[m] for m in sorted(methods)}
        schema["paths"] = sorted_paths

    if "tags" in schema:
        schema["tags"] = sorted(schema["tags"], key=lambda t: t.get("name", ""))

    if "components" in schema and "schemas" in schema["components"]:
        schema["components"]["schemas"] = dict(sorted(schema["components"]["schemas"].items()))

    return schema


def _atomic_write(path: Path, content: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)


# ---------------------------------------------------------------------------
# Auth heuristic for markdown emitter
# ---------------------------------------------------------------------------
# Fallback: assume auth-required unless the path is /healthz or under /auth/.
# The heuristic errs on the side of marking routes as auth-required, which is
# the safer default for this codebase. Routes explicitly in /auth/ are
# session-management endpoints that are intentionally auth-free.


def _is_auth_required(path: str, operation: dict) -> bool:  # noqa: ARG001
    if path == "/healthz":
        return False
    if path.startswith("/auth/"):
        return False
    return True


def _first_sentence(text: str | None) -> str:
    if not text:
        return ""
    text = text.strip()
    # Take up to first blank line or first period
    first_para = text.split("\n\n")[0].strip()
    first_sent = first_para.split(".")[0].strip()
    return first_sent


def _generated_at_iso() -> str:
    """ISO 8601 UTC timestamp truncated to the minute.

    Minute-resolution keeps the diff small when two contributors regenerate
    within the same minute (e.g. CI race) without losing meaningful freshness
    info. If you want second-resolution, drop the ``replace(second=0)``.
    """
    return datetime.now(UTC).replace(second=0, microsecond=0).isoformat().replace("+00:00", "Z")


def _generate_markdown(schema: dict) -> str:
    lines = [
        "---",
        f"last_generated_at: {_generated_at_iso()}",
        "source: backend/scripts/dump_openapi.py",
        "auto_generated: true",
        "---",
        "",
        "# Al Dente API — endpoint reference",
        "",
        "Generated by `backend/scripts/dump_openapi.py`. Do not edit by hand.",
        "",
    ]

    # Group endpoints by tag (sorted); untagged go under "other"
    tag_order: list[str] = [t["name"] for t in schema.get("tags", [])]
    tag_endpoints: dict[str, list[tuple[str, str, dict]]] = {t: [] for t in tag_order}
    tag_endpoints.setdefault("other", [])

    for path, methods in schema.get("paths", {}).items():
        for method, operation in methods.items():
            tags = operation.get("tags", [])
            tag = tags[0] if tags else "other"
            if tag not in tag_endpoints:
                tag_endpoints[tag] = []
            tag_endpoints[tag].append((path, method, operation))

    # Emit sections in tag order, then any extra tags alphabetically
    all_tags = tag_order + sorted(t for t in tag_endpoints if t not in tag_order)
    for tag in all_tags:
        entries = tag_endpoints.get(tag, [])
        if not entries:
            continue
        lines.append(f"## {tag}")
        lines.append("")
        for path, method, operation in sorted(entries, key=lambda x: (x[0], x[1])):
            lines.append(f"### {method.upper()} {path}")
            summary = _first_sentence(operation.get("description") or operation.get("summary"))
            if summary:
                lines.append("")
                lines.append(summary)
            lines.append("")
            auth = _is_auth_required(path, operation)
            lines.append(f"**Auth:** {'required' if auth else 'not required'}")
            if "requestBody" in operation:
                rb = operation["requestBody"]
                content = rb.get("content", {})
                schema_name = ""
                for media_type in content.values():
                    ref = media_type.get("schema", {}).get("$ref", "")
                    if ref:
                        schema_name = ref.split("/")[-1]
                        break
                lines.append(f"**Request body:** {schema_name or 'present'}")
            responses = operation.get("responses", {})
            if responses:
                lines.append(f"**Responses:** {', '.join(str(k) for k in responses)}")
            lines.append("")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    _check_env()
    app = _import_app()

    schema = app.openapi()
    schema = _deterministic_schema(schema)

    json_content = json.dumps(schema, sort_keys=True, indent=2, ensure_ascii=False) + "\n"
    md_content = _generate_markdown(schema)

    DOCS_API_DIR.mkdir(parents=True, exist_ok=True)
    _atomic_write(OPENAPI_JSON, json_content)
    _atomic_write(ENDPOINTS_MD, md_content)

    print(f"[dump_openapi] Wrote {OPENAPI_JSON}")
    print(f"[dump_openapi] Wrote {ENDPOINTS_MD}")


if __name__ == "__main__":
    main()
