"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-05-05

Baseline schema for Al Dente v0.1 — matches SPEC.md §"Data model" verbatim,
plus the throwaway ``pings`` table per CONTEXT.md D-01 (which 01-12 will drop).

Hand-authored (not autogenerated) so PG ENUM type creation is explicit and
ordering of CREATE TYPE / CREATE TABLE statements is deterministic.

7 tables: households, members, recipes, cooking_logs, daily_shortlists, votes, pings
3 enum types: recipe_status, log_rating, vote_value
5 indices: idx_recipes_household_status, idx_recipes_last_cooked,
           idx_logs_household_time, idx_logs_recipe, idx_votes_shortlist
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Locked vocabulary lists — copy of SPEC.md §"Locked vocabularies".
# Used in CHECK constraints; keep in sync with backend/app/models/enums.py
# and frontend/lib/enums.ts.
# ---------------------------------------------------------------------------
CUISINE_VALUES = (
    "italian",
    "french",
    "asian",
    "mediterranean",
    "middleEastern",
    "indian",
    "mexican",
    "northAfrican",
    "american",
    "other",
)
PROTEIN_VALUES = (
    "poultry",
    "redMeat",
    "fish",
    "seafood",
    "egg",
    "legume",
    "none",
)


def upgrade() -> None:
    # ----- Enum types (created up-front so columns can reference them) -----
    op.execute("CREATE TYPE recipe_status AS ENUM ('draft', 'structured', 'verified')")
    op.execute("CREATE TYPE log_rating AS ENUM ('loved', 'liked', 'disliked')")
    op.execute("CREATE TYPE vote_value AS ENUM ('yes', 'no')")

    # ----- households -----
    op.create_table(
        "households",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("invite_code", sa.Text(), nullable=True, unique=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    # ----- members -----
    op.create_table(
        "members",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "household_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("households.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color_hex", sa.Text(), nullable=False),
        sa.Column("auth_token", sa.Text(), nullable=False, unique=True),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    # ----- recipes -----
    cuisine_check = "cuisine IS NULL OR cuisine IN ({values})".format(
        values=", ".join(f"'{v}'" for v in CUISINE_VALUES)
    )
    protein_check = "main_protein IS NULL OR main_protein IN ({values})".format(
        values=", ".join(f"'{v}'" for v in PROTEIN_VALUES)
    )
    op.create_table(
        "recipes",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "household_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("households.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_by_member_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("members.id"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "structured",
                "verified",
                name="recipe_status",
                create_type=False,
            ),
            nullable=False,
            server_default=sa.text("'draft'::recipe_status"),
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_capture", postgresql.JSONB(), nullable=False),
        sa.Column(
            "photo_paths",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column("ingredients", postgresql.JSONB(), nullable=True),
        sa.Column("steps", postgresql.JSONB(), nullable=True),
        sa.Column("prep_time_minutes", sa.Integer(), nullable=True),
        sa.Column("servings", sa.Integer(), nullable=True),
        sa.Column("cuisine", sa.Text(), nullable=True),
        sa.Column(
            "mood",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column("main_protein", sa.Text(), nullable=True),
        sa.Column(
            "seasonality",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{spring,summer,autumn,winter}'"),
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column("last_cooked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cook_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(cuisine_check, name="recipes_cuisine_check"),
        sa.CheckConstraint(protein_check, name="recipes_main_protein_check"),
    )
    op.create_index(
        "idx_recipes_household_status",
        "recipes",
        ["household_id", "status"],
    )
    # last_cooked_at DESC NULLS LAST — mirrors SPEC.md exactly.
    op.execute(
        "CREATE INDEX idx_recipes_last_cooked "
        "ON recipes (household_id, last_cooked_at DESC NULLS LAST)"
    )

    # ----- cooking_logs -----
    op.create_table(
        "cooking_logs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "recipe_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("recipes.id"),
            nullable=False,
        ),
        sa.Column(
            "household_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("households.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "cooked_by_member_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("members.id"),
            nullable=False,
        ),
        sa.Column("cooked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "photo_paths",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column(
            "rating",
            postgresql.ENUM(
                "loved",
                "liked",
                "disliked",
                name="log_rating",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
    )
    op.execute(
        "CREATE INDEX idx_logs_household_time "
        "ON cooking_logs (household_id, cooked_at DESC)"
    )
    op.create_index("idx_logs_recipe", "cooking_logs", ["recipe_id"])

    # ----- daily_shortlists -----
    op.create_table(
        "daily_shortlists",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "household_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("households.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column(
            "recipe_ids",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            nullable=False,
        ),
        sa.Column("filters", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint(
            "household_id",
            "date",
            "generation",
            name="uq_daily_shortlists_hh_date_gen",
        ),
    )

    # ----- votes -----
    op.create_table(
        "votes",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "shortlist_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("daily_shortlists.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "recipe_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("recipes.id"),
            nullable=False,
        ),
        sa.Column(
            "member_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("members.id"),
            nullable=False,
        ),
        sa.Column(
            "vote",
            postgresql.ENUM(
                "yes",
                "no",
                name="vote_value",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("idx_votes_shortlist", "votes", ["shortlist_id"])

    # ----- pings (D-01 throwaway, dropped by 01-12) -----
    op.create_table(
        "pings",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "household_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("households.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "sent_by_member_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("members.id"),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )


def downgrade() -> None:
    # Reverse order: drop dependents before parents, then enum types last.
    op.drop_table("pings")
    op.drop_index("idx_votes_shortlist", table_name="votes")
    op.drop_table("votes")
    op.drop_table("daily_shortlists")
    op.drop_index("idx_logs_recipe", table_name="cooking_logs")
    op.execute("DROP INDEX IF EXISTS idx_logs_household_time")
    op.drop_table("cooking_logs")
    op.execute("DROP INDEX IF EXISTS idx_recipes_last_cooked")
    op.drop_index("idx_recipes_household_status", table_name="recipes")
    op.drop_table("recipes")
    op.drop_table("members")
    op.drop_table("households")

    op.execute("DROP TYPE IF EXISTS vote_value")
    op.execute("DROP TYPE IF EXISTS log_rating")
    op.execute("DROP TYPE IF EXISTS recipe_status")
